/**
 * ⚠️  AUTO-GENERATED — DO NOT EDIT BY HAND
 *
 * Generated by: virellestudios/scripts/sync-mobile-constants.ts
 * Source of truth: virellestudios/server/_core/subscription.ts
 *
 * To update: run `pnpm sync-mobile` in the virellestudios repo,
 * then commit the result in virellestudios-mobile.
 *
 * Last generated: 2026-03-31T08:41:04.315Z
 */

export type SubscriptionTier = "indie" | "amateur" | "independent" | "creator" | "studio" | "industry" | "beta";

export const TIER_DISPLAY_NAMES: Record<string, string> = {
  "indie": "Indie",
  "amateur": "Creator",
  "independent": "Studio",
  "creator": "Studio",
  "studio": "Production",
  "industry": "Enterprise",
  "beta": "Beta"
};

export const TIER_ORDER: SubscriptionTier[] = [
  "indie",
  "amateur",
  "independent",
  "creator",
  "studio",
  "industry",
  "beta"
];

export const SELF_SERVE_TIERS: SubscriptionTier[] = [
  "indie",
  "amateur",
  "independent",
  "creator"
];

/** Monthly credits granted per subscription tier */
export const TIER_MONTHLY_CREDITS: Record<string, number> = {
  "indie": 500,
  "amateur": 2000,
  "independent": 6000,
  "creator": 6000,
  "studio": 15500,
  "industry": 50500,
  "beta": 5000,
  "free": 0
};

/** Pricing in AUD cents */
export const TIER_PRICING = {
  "indie": {
    "monthly": 14900,
    "annual": 12400,
    "annualTotal": 149000,
    "monthlyTotal": 178800,
    "displayName": "Indie"
  },
  "amateur": {
    "monthly": 49000,
    "annual": 40800,
    "annualTotal": 490000,
    "monthlyTotal": 588000,
    "displayName": "Creator"
  },
  "independent": {
    "monthly": 149000,
    "annual": 124100,
    "annualTotal": 1490000,
    "monthlyTotal": 1788000,
    "displayName": "Studio"
  },
  "creator": {
    "monthly": 149000,
    "annual": 124100,
    "annualTotal": 1490000,
    "monthlyTotal": 1788000,
    "displayName": "Studio"
  },
  "studio": {
    "monthly": 0,
    "annual": 0,
    "annualTotal": 15000000,
    "monthlyTotal": 0,
    "displayName": "Production"
  },
  "industry": {
    "monthly": 0,
    "annual": 0,
    "annualTotal": 0,
    "monthlyTotal": 0,
    "displayName": "Enterprise"
  },
  "beta": {
    "monthly": 0,
    "annual": 0,
    "annualTotal": 0,
    "monthlyTotal": 0,
    "displayName": "Beta"
  }
} as const;

/** Feature flags per tier */
export const TIER_LIMITS = {
  "indie": {
    "maxProjects": 2,
    "maxCharactersPerProject": 3,
    "maxScenesPerProject": 3,
    "maxGenerationsPerMonth": 10,
    "maxMovieExports": 0,
    "maxCollaboratorsPerProject": 1,
    "maxScriptsPerProject": 1,
    "maxStorageMB": 500,
    "canUseQuickGenerate": false,
    "canUseTrailerGeneration": false,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": false,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": false,
    "canUseSoundEffects": false,
    "canUseSubtitles": false,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": false,
    "canUseScriptWriter": true,
    "canUseStoryboard": false,
    "canUseCollaboration": false,
    "canExportMovies": false,
    "canExportHD": false,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": false,
    "canUseAISubtitleGen": false,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": false,
    "canUseAIVoiceActing": false,
    "canUseAISoundtrack": false,
    "canUseCharacterConsistency": false,
    "canUseSceneContinuity": false,
    "canUseClipChaining": false,
    "canUseVisualEffects": false,
    "canUseBulkGenerate": false,
    "canUseMultiShotSequencer": false,
    "canUseLiveActionPlate": false,
    "canUseNLEExport": false,
    "canUseAICasting": false,
    "canExportUltraHD": false,
    "canUseWhiteLabel": false,
    "canUseAPIAccess": false,
    "canUseCustomFineTuning": false,
    "canUsePriorityRendering": false,
    "resolution": "720p",
    "quality": [
      "standard"
    ],
    "maxDurationMinutes": 0,
    "maxClipsPerScene": 0,
    "monthlyCredits": 500
  },
  "amateur": {
    "maxProjects": 10,
    "maxCharactersPerProject": 10,
    "maxScenesPerProject": 20,
    "maxGenerationsPerMonth": 100,
    "maxMovieExports": 10,
    "maxCollaboratorsPerProject": 1,
    "maxScriptsPerProject": 5,
    "maxStorageMB": 10000,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": false,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": false,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": false,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": false,
    "canUseBulkGenerate": false,
    "canUseMultiShotSequencer": false,
    "canUseLiveActionPlate": false,
    "canUseNLEExport": false,
    "canUseAICasting": false,
    "canExportUltraHD": false,
    "canUseWhiteLabel": false,
    "canUseAPIAccess": false,
    "canUseCustomFineTuning": false,
    "canUsePriorityRendering": false,
    "resolution": "1080p",
    "quality": [
      "standard",
      "high"
    ],
    "maxDurationMinutes": 90,
    "maxClipsPerScene": 5,
    "monthlyCredits": 2000
  },
  "independent": {
    "maxProjects": 25,
    "maxCharactersPerProject": 30,
    "maxScenesPerProject": 90,
    "maxGenerationsPerMonth": 500,
    "maxMovieExports": 50,
    "maxCollaboratorsPerProject": 5,
    "maxScriptsPerProject": 25,
    "maxStorageMB": 100000,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": true,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": true,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": true,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": true,
    "canUseBulkGenerate": true,
    "canUseMultiShotSequencer": true,
    "canUseLiveActionPlate": true,
    "canUseNLEExport": true,
    "canUseAICasting": true,
    "canExportUltraHD": true,
    "canUseWhiteLabel": false,
    "canUseAPIAccess": false,
    "canUseCustomFineTuning": false,
    "canUsePriorityRendering": true,
    "resolution": "4k",
    "quality": [
      "standard",
      "high",
      "ultra"
    ],
    "maxDurationMinutes": 90,
    "maxClipsPerScene": 10,
    "monthlyCredits": 6000
  },
  "creator": {
    "maxProjects": 25,
    "maxCharactersPerProject": 30,
    "maxScenesPerProject": 90,
    "maxGenerationsPerMonth": 500,
    "maxMovieExports": 50,
    "maxCollaboratorsPerProject": 5,
    "maxScriptsPerProject": 25,
    "maxStorageMB": 100000,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": true,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": true,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": true,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": true,
    "canUseBulkGenerate": true,
    "canUseMultiShotSequencer": true,
    "canUseLiveActionPlate": true,
    "canUseNLEExport": true,
    "canUseAICasting": true,
    "canExportUltraHD": true,
    "canUseWhiteLabel": false,
    "canUseAPIAccess": false,
    "canUseCustomFineTuning": false,
    "canUsePriorityRendering": true,
    "resolution": "4k",
    "quality": [
      "standard",
      "high",
      "ultra"
    ],
    "maxDurationMinutes": 90,
    "maxClipsPerScene": 10,
    "monthlyCredits": 6000
  },
  "studio": {
    "maxProjects": 100,
    "maxCharactersPerProject": 100,
    "maxScenesPerProject": 300,
    "maxGenerationsPerMonth": 2000,
    "maxMovieExports": 200,
    "maxCollaboratorsPerProject": 25,
    "maxScriptsPerProject": 100,
    "maxStorageMB": 500000,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": true,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": true,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": true,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": true,
    "canUseBulkGenerate": true,
    "canUseMultiShotSequencer": true,
    "canUseLiveActionPlate": true,
    "canUseNLEExport": true,
    "canUseAICasting": true,
    "canExportUltraHD": true,
    "canUseWhiteLabel": true,
    "canUseAPIAccess": true,
    "canUseCustomFineTuning": false,
    "canUsePriorityRendering": true,
    "resolution": "4k",
    "quality": [
      "standard",
      "high",
      "ultra"
    ],
    "maxDurationMinutes": 150,
    "maxClipsPerScene": 20,
    "monthlyCredits": 15500
  },
  "industry": {
    "maxProjects": 1000,
    "maxCharactersPerProject": 1000,
    "maxScenesPerProject": 1000,
    "maxGenerationsPerMonth": 10000,
    "maxMovieExports": 1000,
    "maxCollaboratorsPerProject": 1000,
    "maxScriptsPerProject": 1000,
    "maxStorageMB": 5000000,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": true,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": true,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": true,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": true,
    "canUseBulkGenerate": true,
    "canUseMultiShotSequencer": true,
    "canUseLiveActionPlate": true,
    "canUseNLEExport": true,
    "canUseAICasting": true,
    "canExportUltraHD": true,
    "canUseWhiteLabel": true,
    "canUseAPIAccess": true,
    "canUseCustomFineTuning": true,
    "canUsePriorityRendering": true,
    "resolution": "4k",
    "quality": [
      "standard",
      "high",
      "ultra"
    ],
    "maxDurationMinutes": 180,
    "maxClipsPerScene": 50,
    "monthlyCredits": 50500
  },
  "beta": {
    "maxProjects": -1,
    "maxCharactersPerProject": -1,
    "maxScenesPerProject": -1,
    "maxGenerationsPerMonth": -1,
    "maxMovieExports": -1,
    "maxCollaboratorsPerProject": -1,
    "maxScriptsPerProject": -1,
    "maxStorageMB": -1,
    "canUseQuickGenerate": true,
    "canUseTrailerGeneration": true,
    "canUseDirectorAssistant": true,
    "canUseAdPosterMaker": true,
    "canUseBudgetEstimator": true,
    "canUseColorGrading": true,
    "canUseSoundEffects": true,
    "canUseSubtitles": true,
    "canUseDialogueEditor": true,
    "canUseLocationScout": true,
    "canUseMoodBoard": true,
    "canUseShotList": true,
    "canUseContinuityCheck": true,
    "canUseScriptWriter": true,
    "canUseStoryboard": true,
    "canUseCollaboration": true,
    "canExportMovies": true,
    "canExportHD": true,
    "canUseAICharacterGen": true,
    "canUseAIScriptGen": true,
    "canUseAIDialogueGen": true,
    "canUseAIBudgetGen": true,
    "canUseAISubtitleGen": true,
    "canUseAILocationSuggest": true,
    "canUseFullFilmGeneration": true,
    "canUseAIVoiceActing": true,
    "canUseAISoundtrack": true,
    "canUseCharacterConsistency": true,
    "canUseSceneContinuity": true,
    "canUseClipChaining": true,
    "canUseVisualEffects": true,
    "canUseBulkGenerate": true,
    "canUseMultiShotSequencer": true,
    "canUseLiveActionPlate": true,
    "canUseNLEExport": true,
    "canUseAICasting": true,
    "canExportUltraHD": true,
    "canUseWhiteLabel": true,
    "canUseAPIAccess": true,
    "canUseCustomFineTuning": true,
    "canUsePriorityRendering": true,
    "resolution": "4k",
    "quality": [
      "standard",
      "high",
      "ultra"
    ],
    "maxDurationMinutes": 180,
    "maxClipsPerScene": 12,
    "monthlyCredits": 5000
  }
} as const;

/** Credit costs per action */
export const CREDIT_COSTS = {
  "generate_film": {
    "cost": 10,
    "label": "Generate Film (AI scene breakdown + script, full pipeline)"
  },
  "generate_scene_video": {
    "cost": 10,
    "label": "Generate Scene Video (≤45s; longer scenes cost more)"
  },
  "regenerate_scene_video": {
    "cost": 8,
    "label": "Regenerate Scene Video (≤45s; 80% of generate cost)"
  },
  "generate_preview_image": {
    "cost": 3,
    "label": "Generate Preview Image (DALL-E 3 HD)"
  },
  "bulk_generate_previews": {
    "cost": 3,
    "label": "Bulk Generate Previews (per scene — image only)"
  },
  "bulk_generate_videos": {
    "cost": 10,
    "label": "Bulk Generate Videos (per scene — duration-scaled)"
  },
  "virelle_chat": {
    "cost": 2,
    "label": "Virelle AI Chat / Director Assistant (per message)"
  },
  "director_assistant": {
    "cost": 2,
    "label": "Director's Assistant SSE stream message"
  },
  "voice_tts": {
    "cost": 2,
    "label": "Voice TTS synthesis (ElevenLabs / OpenAI)"
  },
  "script_writer_ai": {
    "cost": 8,
    "label": "AI Script Writer (full screenplay generation)"
  },
  "storyboard_ai": {
    "cost": 8,
    "label": "AI Storyboard Generation (full visual breakdown)"
  },
  "dialogue_editor_ai": {
    "cost": 5,
    "label": "AI Dialogue Polish (scene-level rewrite)"
  },
  "continuity_check_ai": {
    "cost": 5,
    "label": "AI Continuity Check (full film analysis)"
  },
  "shot_list_ai": {
    "cost": 5,
    "label": "AI Shot List Generation (per scene)"
  },
  "character_gen_ai": {
    "cost": 5,
    "label": "AI Character Generation (image + bio)"
  },
  "location_scout_ai": {
    "cost": 3,
    "label": "AI Location Scout (suggestions + reference image)"
  },
  "budget_estimate_ai": {
    "cost": 5,
    "label": "AI Budget Estimate (multi-scene analysis)"
  },
  "subtitle_gen_ai": {
    "cost": 8,
    "label": "AI Subtitle Generation (full film, large context)"
  },
  "trailer_gen": {
    "cost": 20,
    "label": "Trailer Generation (4–6 video clips, ~2 min cinematic)"
  },
  "ad_poster_gen": {
    "cost": 5,
    "label": "Ad/Poster Image Generation (DALL-E 3 HD)"
  },
  "ad_poster_copy_gen": {
    "cost": 3,
    "label": "Ad/Poster Copy Generation (AI tagline + description)"
  },
  "ad_poster_video_gen": {
    "cost": 10,
    "label": "Ad/Poster Video Ad Generation (video clip via BYOK)"
  },
  "tagline_variants_gen": {
    "cost": 3,
    "label": "AI Tagline Variants (5 distinct tagline options)"
  },
  "brand_kit_gen": {
    "cost": 5,
    "label": "AI Brand Kit Generation (palette + fonts + logo concept)"
  },
  "influencer_kit_gen": {
    "cost": 5,
    "label": "AI Influencer Kit Generation (press release + social copy)"
  },
  "sfx_generate_from_text": {
    "cost": 5,
    "label": "AI Sound Effect Generation (ElevenLabs text-to-SFX)"
  },
  "sfx_voice_choir": {
    "cost": 5,
    "label": "AI Voice Choir Generation (ElevenLabs TTS choir/wings)"
  },
  "film_post_adr_suggest": {
    "cost": 5,
    "label": "AI ADR Suggestions (dialogue replacement analysis per project)"
  },
  "film_post_foley_suggest": {
    "cost": 5,
    "label": "AI Foley Suggestions (sound design analysis per project)"
  },
  "film_post_score_gen": {
    "cost": 8,
    "label": "AI Score Cue Generation (music cue breakdown per project)"
  },
  "film_post_mix_export": {
    "cost": 2,
    "label": "Mix Summary Export (structured post-production report)"
  },
  "funding_app_submit": {
    "cost": 10,
    "label": "Funding Application Submit (compiled pack + email delivery)"
  },
  "blog_article_gen": {
    "cost": 5,
    "label": "Blog Article Generation (full article, ~1500 words)"
  },
  "export_final_film": {
    "cost": 8,
    "label": "Export Final Film (full assembly + render)"
  },
  "create_project": {
    "cost": 0,
    "label": "Create New Project (FREE — no friction on start)"
  },
  "movie_export": {
    "cost": 5,
    "label": "Movie Export (scenes/trailer export)"
  }
} as const;

/** One-time top-up packs */
export const TOP_UP_PACKS = [
  {
    "id": "topup_10",
    "name": "Starter Pack",
    "credits": 500,
    "price": 75000,
    "pricePerCredit": 1.5,
    "savings": ""
  },
  {
    "id": "topup_50",
    "name": "Producer Pack",
    "credits": 1500,
    "price": 180000,
    "pricePerCredit": 1.2,
    "savings": "Save 20%"
  },
  {
    "id": "topup_100",
    "name": "Director Pack",
    "credits": 3000,
    "price": 315000,
    "pricePerCredit": 1.05,
    "savings": "Save 30%"
  },
  {
    "id": "topup_200",
    "name": "Studio Pack",
    "credits": 6000,
    "price": 540000,
    "pricePerCredit": 0.9,
    "savings": "Save 40%"
  },
  {
    "id": "topup_500",
    "name": "Blockbuster Pack",
    "credits": 12000,
    "price": 900000,
    "pricePerCredit": 0.75,
    "savings": "Save 50%"
  },
  {
    "id": "topup_1000",
    "name": "Mogul Pack",
    "credits": 25000,
    "price": 1500000,
    "pricePerCredit": 0.6,
    "savings": "Save 60%"
  }
] as const;

/** Referral reward config */
export const REFERRAL_REWARDS = {
  "referrerCredits": 7000,
  "newUserCredits": 7000,
  "maxReferralsPerMonth": 50,
  "milestones": [
    {
      "count": 3,
      "bonus": 25000,
      "label": "Rising Star"
    },
    {
      "count": 5,
      "bonus": 50000,
      "label": "Connector"
    },
    {
      "count": 10,
      "bonus": 150000,
      "label": "Ambassador"
    },
    {
      "count": 25,
      "bonus": 500000,
      "label": "Legend"
    }
  ]
} as const;

export const LAUNCH_SPECIAL_ACTIVE = true;
export const LAUNCH_SPECIAL_DISCOUNT = 0.5;

/**
 * Returns true if a user's tier can access a given feature.
 * Mirrors isSelfServeTier() and TIER_LIMITS checks from the web server.
 */
export function tierHasFeature(
  userTier: string,
  feature: keyof typeof TIER_LIMITS["indie"]
): boolean {
  const limits = TIER_LIMITS[userTier as SubscriptionTier];
  if (!limits) return false;
  const val = limits[feature];
  return val !== false && val !== 0;
}

/**
 * Returns true if userTier meets or exceeds the required minTier.
 */
export function tierMeetsMinimum(
  userTier: string,
  minTier: SubscriptionTier
): boolean {
  const userIdx = TIER_ORDER.indexOf(userTier as SubscriptionTier);
  const minIdx = TIER_ORDER.indexOf(minTier);
  if (userIdx === -1 || minIdx === -1) return false;
  return userIdx >= minIdx;
}
